name: Test

on: push

jobs:
  test:
    name: Pester
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zyborg/pester-tests-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
